### PR TITLE
feat(core): add command to get package versions

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/muffin-crusaders/glitch/24)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[package.json, line 3 \[r1\]](https://reviewable.io:443/reviews/muffin-crusaders/glitch/24#-K1F1p63OWwxZIxd8s1_)** ([raw file](https://github.com/muffin-crusaders/glitch/blob/20d63963e01be87b6463ba1b975732eb54f17970/package.json#L3)):</sup>
We should start bumping glitch version itself.


---

<sup>**[scripts/example.coffee, line 18 \[r1\]](https://reviewable.io:443/reviews/muffin-crusaders/glitch/24#-K1F1yICB5a5v29p8n6I)** ([raw file](https://github.com/muffin-crusaders/glitch/blob/20d63963e01be87b6463ba1b975732eb54f17970/scripts/example.coffee#L18)):</sup>
When checking for package, if not found, try prepending `hubot-` and checking again. Most hubot pacakages are named `hubot-x` after all. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/glitch/24)

**Comment by spencerwahl** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[package.json, line 3 \[r1\]](https://reviewable.io:443/reviews/muffin-crusaders/glitch/24#-K1F1p63OWwxZIxd8s1_)** ([raw file](https://github.com/muffin-crusaders/glitch/blob/20d63963e01be87b6463ba1b975732eb54f17970/package.json#L3)):</sup>
Should I add the version update to this PR or separate it?


---

<sup>**[scripts/example.coffee, line 18 \[r1\]](https://reviewable.io:443/reviews/muffin-crusaders/glitch/24#-K1F1yICB5a5v29p8n6I)** ([raw file](https://github.com/muffin-crusaders/glitch/blob/20d63963e01be87b6463ba1b975732eb54f17970/scripts/example.coffee#L18)):</sup>
done


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/glitch/24)

**Comment by AleksueiR** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[package.json, line 3 \[r1\]](https://reviewable.io:443/reviews/muffin-crusaders/glitch/24#-K1F1p63OWwxZIxd8s1_)** ([raw file](https://github.com/muffin-crusaders/glitch/blob/20d63963e01be87b6463ba1b975732eb54f17970/package.json#L3)):</sup>
Add here.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/glitch/24)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/glitch/24)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/glitch/24)

**Pull request merged**
