### PR TITLE
feat(funnel): fix github username regex

### PR DESCRIPTION
**Pull request by AleksueiR**
Also added "unassigned" to issues regex.

[Review on Reviewable](https://reviewable.io/reviews/muffin-crusaders/glitch/9)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[scripts/gitter-activity-notifier.coffee, line 52 \[r1\]](https://reviewable.io:443/reviews/muffin-crusaders/glitch/9#-K-Z29CRbl6Z_ewE5SY5)** ([raw file](https://github.com/muffin-crusaders/glitch/blob/88e7b15015414c3ead13edb9cdf0f3381d2e9ced/scripts/gitter-activity-notifier.coffee#L52)):</sup>
Should this be \w[\w-]* instead?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/glitch/9)

**Comment by AleksueiR** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[scripts/gitter-activity-notifier.coffee, line 52 \[r1\]](https://reviewable.io:443/reviews/muffin-crusaders/glitch/9#-K-Z29CRbl6Z_ewE5SY5)** ([raw file](https://github.com/muffin-crusaders/glitch/blob/88e7b15015414c3ead13edb9cdf0f3381d2e9ced/scripts/gitter-activity-notifier.coffee#L52)):</sup>
Can you have a one-letter github username?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/glitch/9)

**Comment by spencerwahl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[scripts/gitter-activity-notifier.coffee, line 52 \[r1\]](https://reviewable.io:443/reviews/muffin-crusaders/glitch/9#-K-Z29CRbl6Z_ewE5SY5)** ([raw file](https://github.com/muffin-crusaders/glitch/blob/88e7b15015414c3ead13edb9cdf0f3381d2e9ced/scripts/gitter-activity-notifier.coffee#L52)):</sup>
Whoops, confused myself and thought \w matched whole words. We probably don't have to worry about one-letter usernames.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/glitch/9)

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/glitch/9)

**Comment by AleksueiR** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[scripts/gitter-activity-notifier.coffee, line 52 \[r1\]](https://reviewable.io:443/reviews/muffin-crusaders/glitch/9#-K-Z29CRbl6Z_ewE5SY5)** ([raw file](https://github.com/muffin-crusaders/glitch/blob/88e7b15015414c3ead13edb9cdf0f3381d2e9ced/scripts/gitter-activity-notifier.coffee#L52)):</sup>
In the worst case it won't work for 26 users :D


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/glitch/9)

**Pull request merged**
